// web/src/pages/Doctor.tsx
import { useState } from 'react';
import {
  Stethoscope,
  Play,
  CheckCircle,
  AlertTriangle,
  XCircle,
  Loader2,
} from 'lucide-react';
import type { DiagResult } from '@/types/api';
import { runDoctor } from '@/lib/api';

function severityIcon(severity: DiagResult['severity']) {
  switch (severity) {
    case 'ok':
      return <CheckCircle className="h-4 w-4 text-green-400 flex-shrink-0" />;
    case 'warn':
      return <AlertTriangle className="h-4 w-4 text-yellow-400 flex-shrink-0" />;
    case 'error':
      return <XCircle className="h-4 w-4 text-red-400 flex-shrink-0" />;
  }
}

function severityBorder(severity: DiagResult['severity']): string {
  switch (severity) {
    case 'ok':
      return 'border-green-700/40';
    case 'warn':
      return 'border-yellow-700/40';
    case 'error':
      return 'border-red-700/40';
  }
}

function severityBg(severity: DiagResult['severity']): string {
  switch (severity) {
    case 'ok':
      return 'bg-green-900/10';
    case 'warn':
      return 'bg-yellow-900/10';
    case 'error':
      return 'bg-red-900/10';
  }
}

export default function Doctor() {
  const [results, setResults] = useState<DiagResult[] | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const handleRun = async () => {
    setLoading(true);
    setError(null);
    setResults(null);
    try {
      const data = await runDoctor();
      setResults(data);
    } catch (err: unknown) {
      setError(err instanceof Error ? err.message : 'Failed to run diagnostics');
    } finally {
      setLoading(false);
    }
  };

  // Compute summary counts
  const okCount = results?.filter((r) => r.severity === 'ok').length ?? 0;
  const warnCount = results?.filter((r) => r.severity === 'warn').length ?? 0;
  const errorCount = results?.filter((r) => r.severity === 'error').length ?? 0;

  // Group by category
  const grouped =
    results?.reduce<Record<string, DiagResult[]>>((acc, item) => {
      const key = item.category;
      if (!acc[key]) acc[key] = [];
      acc[key].push(item);
      return acc;
    }, {}) ?? {};

  return (
    <div className="p-6 space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2">
          <Stethoscope className="h-5 w-5 text-blue-400" />
          <h2 className="text-base font-semibold text-white">Diagnostics</h2>
        </div>
        <button
          onClick={handleRun}
          disabled={loading}
          className="flex items-center gap-2 bg-blue-600 hover:bg-blue-700 text-white text-sm font-medium px-4 py-2 rounded-lg transition-colors disabled:opacity-50"
        >
          {loading ? (
            <>
              <Loader2 className="h-4 w-4 animate-spin" />
              Running...
            </>
          ) : (
            <>
              <Play className="h-4 w-4" />
              Run Diagnostics
            </>
          )}
        </button>
      </div>

      {/* Error */}
      {error && (
        <div className="rounded-lg bg-red-900/30 border border-red-700 p-4 text-red-300">
          {error}
        </div>
      )}

      {/* Loading spinner */}
      {loading && (
        <div className="flex flex-col items-center justify-center py-16">
          <Loader2 className="h-10 w-10 text-blue-500 animate-spin mb-4" />
          <p className="text-gray-400">Running diagnostics...</p>
          <p className="text-sm text-gray-500 mt-1">
            This may take a few seconds.
          </p>
        </div>
      )}

      {/* Results */}
      {results && !loading && (
        <>
          {/* Summary Bar */}
          <div className="flex items-center gap-4 bg-gray-900 rounded-xl border border-gray-800 p-4">
            <div className="flex items-center gap-2">
              <CheckCircle className="h-5 w-5 text-green-400" />
              <span className="text-sm text-white font-medium">
                {okCount} <span className="text-gray-400 font-normal">ok</span>
              </span>
            </div>
            <div className="w-px h-5 bg-gray-700" />
            <div className="flex items-center gap-2">
              <AlertTriangle className="h-5 w-5 text-yellow-400" />
              <span className="text-sm text-white font-medium">
                {warnCount}{' '}
                <span className="text-gray-400 font-normal">
                  warning{warnCount !== 1 ? 's' : ''}
                </span>
              </span>
            </div>
            <div className="w-px h-5 bg-gray-700" />
            <div className="flex items-center gap-2">
              <XCircle className="h-5 w-5 text-red-400" />
              <span className="text-sm text-white font-medium">
                {errorCount}{' '}
                <span className="text-gray-400 font-normal">
                  error{errorCount !== 1 ? 's' : ''}
                </span>
              </span>
            </div>

            {/* Overall indicator */}
            <div className="ml-auto">
              {errorCount > 0 ? (
                <span className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-xs font-medium bg-red-900/40 text-red-400 border border-red-700/50">
                  Issues Found
                </span>
              ) : warnCount > 0 ? (
                <span className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-xs font-medium bg-yellow-900/40 text-yellow-400 border border-yellow-700/50">
                  Warnings
                </span>
              ) : (
                <span className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-xs font-medium bg-green-900/40 text-green-400 border border-green-700/50">
                  All Clear
                </span>
              )}
            </div>
          </div>

          {/* Grouped Results */}
          {Object.entries(grouped)
            .sort(([a], [b]) => a.localeCompare(b))
            .map(([category, items]) => (
              <div key={category}>
                <h3 className="text-sm font-semibold text-gray-400 uppercase tracking-wider mb-3 capitalize">
                  {category}
                </h3>
                <div className="space-y-2">
                  {items.map((result, idx) => (
                    <div
                      key={`${category}-${idx}`}
                      className={`flex items-start gap-3 rounded-lg border p-3 ${severityBorder(
                        result.severity,
                      )} ${severityBg(result.severity)}`}
                    >
                      {severityIcon(result.severity)}
                      <div className="min-w-0">
                        <p className="text-sm text-white">{result.message}</p>
                        <p className="text-xs text-gray-500 mt-0.5 capitalize">
                          {result.severity}
                        </p>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            ))}
        </>
      )}

      {/* Empty state */}
      {!results && !loading && !error && (
        <div className="flex flex-col items-center justify-center py-16 text-gray-500">
          <Stethoscope className="h-12 w-12 text-gray-600 mb-4" />
          <p className="text-lg font-medium">System Diagnostics</p>
          <p className="text-sm mt-1">
            Click "Run Diagnostics" to check your Gloamy installation.
          </p>
        </div>
      )}
    </div>
  );
}

// desktop/src/pages/doctor.vue
<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import { Icon } from '@iconify/vue'
import { useAuthStore } from '@/stores/auth'

type Severity = 'ok' | 'warn' | 'error'

interface DiagnosticResult {
  name: string
  severity: Severity
  message: string
  suggestion?: string
}

interface DoctorResponse {
  results: DiagnosticResult[]
  summary: {
    ok: number
    warnings: number
    errors: number
  }
}

const auth = useAuthStore()
const results = ref<DiagnosticResult[]>([])
const summary = ref<{ ok: number; warnings: number; errors: number }>({ ok: 0, warnings: 0, errors: 0 })
const loading = ref(true)
const error = ref<string | null>(null)
const activeFilter = ref<'all' | Severity>('all')

const filters: Array<'all' | Severity> = ['all', 'ok', 'warn', 'error']

const filteredResults = computed(() => {
  if (activeFilter.value === 'all') return results.value
  return results.value.filter(r => r.severity === activeFilter.value)
})

function severityIcon(severity: Severity): string {
  switch (severity) {
    case 'ok': return 'ph:check-circle'
    case 'warn': return 'ph:warning'
    case 'error': return 'ph:x-circle'
  }
}

function severityColor(severity: Severity): string {
  switch (severity) {
    case 'ok': return 'text-emerald-500'
    case 'warn': return 'text-amber-500'
    case 'error': return 'text-red-500'
  }
}

function filterLabel(filter: 'all' | Severity): string {
  switch (filter) {
    case 'all': return 'All'
    case 'ok': return 'Passed'
    case 'warn': return 'Warnings'
    case 'error': return 'Errors'
  }
}

function filterCount(filter: 'all' | Severity): number {
  switch (filter) {
    case 'all': return results.value.length
    case 'ok': return summary.value.ok
    case 'warn': return summary.value.warnings
    case 'error': return summary.value.errors
  }
}

async function runDiagnostics() {
  loading.value = true
  error.value = null
  try {
    const response = await auth.fetchWithAuth<DoctorResponse>('/api/doctor', { method: 'POST' })
    results.value = response.results || []
    summary.value = response.summary || { ok: 0, warnings: 0, errors: 0 }
  } catch (err: any) {
    console.error('[doctor] runDiagnostics error:', err)
    error.value = err.message || 'Failed to run diagnostics'
    results.value = []
  } finally {
    loading.value = false
  }
}

onMounted(() => {
  runDiagnostics()
})
</script>

<template>
  <div class="h-full flex flex-col overflow-hidden bg-background text-[15px]">
    <!-- Header -->
    <div class="flex-shrink-0 px-6 pt-6 pb-4">
      <div class="flex items-center justify-between mb-4">
        <div>
          <h1 class="text-lg font-semibold text-foreground">Diagnostics</h1>
          <p class="text-[13px] text-muted-foreground">System health checks and configuration validation</p>
        </div>
        <button
          @click="runDiagnostics"
          :disabled="loading"
          class="flex items-center gap-1.5 px-3 py-1.5 text-[12px] font-medium rounded-md text-muted-foreground hover:text-foreground transition-colors disabled:opacity-50"
        >
          <Icon icon="ph:arrow-clockwise" class="size-3.5" :class="{ 'animate-spin': loading }" />
          Run Again
        </button>
      </div>

      <!-- Filters -->
      <div class="flex items-center gap-1">
        <button
          v-for="filter in filters"
          :key="filter"
          @click="activeFilter = filter"
          class="px-3 py-1.5 text-[12px] font-medium rounded-md whitespace-nowrap transition-colors flex items-center gap-1.5"
          :class="activeFilter === filter
            ? 'text-foreground'
            : 'text-muted-foreground hover:text-foreground'"
        >
          {{ filterLabel(filter) }}
          <span class="text-[10px] opacity-70">({{ filterCount(filter) }})</span>
        </button>
      </div>
    </div>

    <!-- Loading state -->
    <div v-if="loading" class="flex-1 overflow-y-auto px-6 py-4">
      <!-- Skeleton filter tabs -->
      <div class="flex items-center gap-1 mb-6">
        <div v-for="i in 4" :key="i" class="h-6 bg-muted-foreground/10 rounded-sm animate-pulse w-20" />
      </div>
      <!-- Skeleton results -->
      <div v-for="i in 6" :key="i" class="flex items-start gap-3 py-3">
        <div class="size-4 mt-0.5 bg-muted-foreground/10 rounded-sm animate-pulse flex-shrink-0" />
        <div class="flex-1 min-w-0">
          <div class="h-4 bg-muted-foreground/10 rounded-sm animate-pulse w-32 mb-2" />
          <div class="h-3 bg-muted-foreground/10 rounded-sm animate-pulse w-3/4" />
        </div>
      </div>
    </div>

    <!-- Content -->
    <div v-else class="flex-1 overflow-y-auto px-6 py-4">
      <!-- Error -->
      <div v-if="error" class="mb-4 px-3 py-2 text-[12px] text-amber-500 flex items-center gap-2">
        <Icon icon="ph:warning" class="size-4" />
        <span>{{ error }}</span>
      </div>

      <!-- Empty state -->
      <div v-if="filteredResults.length === 0 && !error" class="flex flex-col items-center justify-center py-16">
        <Icon icon="ph:stethoscope" class="size-12 text-muted-foreground/30 mb-3" />
        <p class="text-muted-foreground text-[13px]">No diagnostics to display</p>
      </div>

      <!-- Results list -->
      <div v-else class="space-y-1">
        <div
          v-for="(result, index) in filteredResults"
          :key="index"
          class="flex items-start gap-3 py-3"
        >
          <Icon
            :icon="severityIcon(result.severity)"
            class="size-4 mt-0.5 flex-shrink-0"
            :class="severityColor(result.severity)"
          />
          <div class="flex-1 min-w-0">
            <div class="flex items-center gap-2">
              <span class="text-[13px] font-medium text-foreground">{{ result.name }}</span>
            </div>
            <p class="text-[12px] text-muted-foreground mt-0.5">{{ result.message }}</p>
            <p v-if="result.suggestion" class="text-[11px] text-muted-foreground/70 mt-1">
              {{ result.suggestion }}
            </p>
          </div>
        </div>
      </div>

      <!-- Summary -->
      <div v-if="results.length > 0" class="mt-6 pt-4 text-[11px] text-muted-foreground flex items-center gap-4">
        <span class="flex items-center gap-1">
          <Icon icon="ph:check-circle" class="size-3 text-emerald-500" />
          {{ summary.ok }} passed
        </span>
        <span v-if="summary.warnings > 0" class="flex items-center gap-1">
          <Icon icon="ph:warning" class="size-3 text-amber-500" />
          {{ summary.warnings }} warnings
        </span>
        <span v-if="summary.errors > 0" class="flex items-center gap-1">
          <Icon icon="ph:x-circle" class="size-3 text-red-500" />
          {{ summary.errors }} errors
        </span>
      </div>
    </div>
  </div>
</template>
